services:
    appuser.form.registration:
        class: User\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    appuser.form.profile:
        class: User\UserBundle\Form\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_profile }