<?php

namespace Main\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityProposalRepository extends EntityRepository
{
}
