<?php

namespace Main\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVARepository extends EntityRepository
{
}
