admin_activity_index:
    path:     /
    defaults: { _controller: "MainBundle:ActivityAdmin:index" }
    methods:  GET

admin_activity_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:ActivityAdmin:show" }
    methods:  GET

admin_activity_new:
    path:     /new
    defaults: { _controller: "MainBundle:ActivityAdmin:new" }
    methods:  [GET, POST]

admin_activity_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:ActivityAdmin:edit" }
    methods:  [GET, POST]

admin_activity_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:ActivityAdmin:delete" }
    methods:  DELETE